/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

// ABI re-exports for COMPUT3 contracts deployed on Base Sepolia
export { default as ProviderRegistryABI } from "./ProviderRegistry.json";
export { default as DeploymentEscrowABI } from "./DeploymentEscrow.json";
export { default as deployments } from "./deployments.json";
